#! /usr/bin/env python

"""
Nagios plugin to check the DNS values for a host from 2 or more DNS servers.

Copyright (c) 2008 Peter Kropf. All rights reserved.

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.

Example:

Check the "hostname" IP address as returned by dns.server.one and
dns.server.two.
    
    ./check_crossdbs.py hostname dns.server.one dns.server.two
"""


import DNS
import sys
from optparse import OptionParser

prefix = 'CROSSDNS'

class nagios:
    ok       = (0, 'OK')
    warning  = (1, 'WARNING')
    critical = (2, 'CRITICAL')
    unknown  = (3, 'UNKNOWN')


def exit(status, message):
    print prefix + ' ' + status[1] + ' - ' + message
    sys.exit(status[0])


parser = OptionParser(usage='usage: %prog host dns_server_1 dns_server_2 . . .')
options, args = parser.parse_args()


if len(sys.argv) < 4:
    exit(nagios.unknown, 'missing command line arguments')

host = args[0]
servers = args[1:]
dns = DNS.Request(host)

try:
    resp = [(s, dns.req(server=s)) for s in servers]
except DNS.Base.DNSError, ex:
    exit(nagios.unknown, str(ex) + ', ' + s)

unknown = [r[0] for r in resp if len(r[1].answers) == 0]
if len(unknown):
    exit(nagios.critical, str(unknown) + " doesn't know " + host)

ips = list(set([i[1].answers[0]['data'] for i in resp]))
if len(ips) > 1:
    exit(nagios.critical, host + ' has multiple ip addresses - ' + str(ips))

exit(nagios.ok, host + ': ' + str(ips))
