#! /usr/bin/env python

"""
Nagios plugin to check the temperature in the server room.

Copyright (c) 2009 Peter Kropf. All rights reserved.

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.

Example:

Check the temperature as recorded in /var/temperature/latest to ensure that
it's within the specified range.

    ./check_temperature.py low high
"""


import sys
from optparse import OptionParser

prefix = 'TEMPERATURE'

class nagios:
    ok       = (0, 'OK')
    warning  = (1, 'WARNING')
    critical = (2, 'CRITICAL')
    unknown  = (3, 'UNKNOWN')


def exit(status, message):
    print prefix + ' ' + status[1] + ' - ' + message
    sys.exit(status[0])

parser = OptionParser(usage='usage: %prog low high . . .')
parser.add_option('-w', dest='warning',     type='float',   help='warning level.')
parser.add_option('-c', dest='critical',    type='float',   help='critical level.')
options, args = parser.parse_args()

try:
    stemperature = open('/var/temperature/latest', 'r').read()
    temperature = float(stemperature)
except Exception, ex:
    exit(nagios.unknown, str(ex) + ', ' + s)


if options.critical:
    if temperature > options.critical:
        exit(nagios.critical, 'temperature too high: ' + stemperature)

if options.warning:
    if temperature > options.warning:
        exit(nagios.warning, 'temperature getting high: ' + stemperature)

exit(nagios.ok, stemperature)
