#! /usr/bin/env python

import os
import ow
from datetime import datetime

ow.init('u')
ow.opt('F')

t = ow.Sensor('/10.54BA4D000800')
temperature = t.temperature

f = open('/var/temperature/latest', 'w')
f.write('%f' % float(temperature))
f.close()

f = open('/var/temperature/log', 'a')
f.write('%s %f%s' % (str(datetime.now()), float(temperature), os.linesep))
f.close()
